from reportlab.lib.pagesizes import A4, landscape
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor, white, black, grey
from reportlab.lib.units import inch
import os

def generate_schema_pdf():
    filename = "Database_Schema_Structure.pdf"
    c = canvas.Canvas(filename, pagesize=landscape(A4))
    width, height = landscape(A4)

    # Colors
    HEADER_GOLD = HexColor("#F4B942")
    NAVY = HexColor("#2C3E50")
    CSV_COLOR = HexColor("#E8F6F3") # Light Teal
    SQL_COLOR = HexColor("#FDF2E9") # Light Orange
    LINK_COLOR = HexColor("#3498DB")

    # Header
    c.setFont("Helvetica-Bold", 24)
    c.setFillColor(NAVY)
    c.drawCentredString(width/2, height - 0.8*inch, "Database & Data Flow Structure")
    
    c.setFont("Helvetica", 12)
    c.setFillColor(grey)
    c.drawCentredString(width/2, height - 1.1*inch, "Hybrid CSV & SQLite Integration for SIP2LIFE DISTILLERIES PVT. LTD.")

    def draw_table(x, y, title, columns, color, w=150):
        h = 25 + (len(columns) * 15)
        c.setStrokeColor(black)
        c.setFillColor(color)
        c.rect(x, y-h, w, h, fill=1, stroke=1)
        
        # Title bar
        c.setFillColor(NAVY)
        c.rect(x, y-25, w, 25, fill=1, stroke=1)
        c.setFillColor(white)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(x+5, y-17, title)
        
        # Columns
        c.setFillColor(black)
        c.setFont("Helvetica", 9)
        curr_y = y - 40
        for col in columns:
            c.drawString(x+10, curr_y, f"• {col}")
            curr_y -= 15
        return x, y, w, h

    # Section Labels
    c.setFont("Helvetica-Bold", 14)
    c.setFillColor(HexColor("#16A085"))
    c.drawString(1*inch, height - 1.6*inch, "A. Operational Trackers (CSV Files)")
    
    c.setFillColor(HexColor("#D35400"))
    c.drawString(5.5*inch, height - 1.6*inch, "B. Financial & Inventory Ledgers (SQLite)")

    # --- CSV TABLES ---
    draw_table(0.5*inch, height - 2*inch, "reg76_data.csv", 
               ["reg76_id (PK)", "permit_no", "pass_no", "bl_receipt", "al_receipt"], CSV_COLOR)
    
    draw_table(2.7*inch, height - 2*inch, "reg74_data.csv", 
               ["reg74_id (PK)", "batch_no (UK)", "source_vat", "closing_bl", "wastage_al"], HEADER_GOLD)

    draw_table(2.7*inch, height - 4.5*inch, "rega_data.csv", 
               ["rega_id (PK)", "batch_no (FK)", "brand_name", "total_bottles", "wastage_al"], CSV_COLOR)

    draw_table(0.5*inch, height - 4.5*inch, "reg78_data.csv", 
               ["reg78_id (PK)", "synopsis_date", "total_fees", "opening_bl", "closing_bl"], CSV_COLOR)

    # --- SQLITE TABLES ---
    draw_table(5.5*inch, height - 2*inch, "regb_bottle_stock", 
               ["regb_id (PK)", "product_name", "qty_received", "qty_issued", "closing_bal"], SQL_COLOR)

    draw_table(8*inch, height - 2*inch, "regb_production_fees", 
               ["fees_id (PK)", "opening_bal", "fee_debited", "closing_bal"], SQL_COLOR)

    draw_table(6.75*inch, height - 4.5*inch, "excise_duty_ledger", 
               ["duty_id (PK)", "date", "opening_bal", "duty_debited", "closing_bal"], SQL_COLOR)

    # Draw Logic Lines (Relational)
    c.setStrokeColor(LINK_COLOR)
    c.setLineWidth(1.5)
    
    # 76 to 74
    c.line(2*inch, height-2.5*inch, 2.7*inch, height-2.5*inch)
    
    # 74 to A (Batch Link)
    c.line(3.5*inch, height-3.7*inch, 3.5*inch, height-4.5*inch)
    
    # A to RegB
    c.line(4.7*inch, height-5*inch, 5.5*inch, height-2.5*inch)
    
    # A to Reg78
    c.line(2.7*inch, height-5*inch, 2*inch, height-5*inch)
    
    # RegB to Duty
    c.line(6.5*inch, height-3.7*inch, 6.75*inch, height-4.5*inch)

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(grey)
    c.drawString(1*inch, 0.4*inch, "Generated by Antigravity AI - System Database Schema v2.0")

    c.save()

if __name__ == "__main__":
    generate_schema_pdf()
